### ISSUE TITLE
TeamTreeHouse Java Coursework

### ISSUE THREAD

**Issue by FlyingHammer** [FlyingHammer/TreehouseJava#1]
## Todo
- Courses left to complete
- [x] Java Basics
- [ ] Java Objects
- [ ] Java Data Structures
- [ ] Local Development Environments
- [ ] Build a JavaFx Application

:+1: 
cc @gmckay
